[program:code-server]
command=code-server --bind-addr 127.0.0.1:10001 --auth none --config /home/ubuntu/.code-server/config.yaml --user-data-dir /home/ubuntu/.code-server --extensions-dir /opt/code-server-extensions /home/ubuntu/projects
directory=/home/ubuntu/projects
user=ubuntu
environment=HOME="/home/ubuntu"
priority=200
autostart=true
autorestart=true
startretries=3
startsecs=10
stdout_logfile=/tmp/code-server_stdout.log
stderr_logfile=/tmp/code-server_stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
